-- Rahma Traveler PostgreSQL schema
-- Generated from SQLite metadata: apps/api/instance/rahma_traveler_dev.db
-- Tables: assignment_history, booking_event_trail, booking_status_history, ce_bookings, community_events, dm_copy_library, handoff_queue, interactions, language_templates, leads, sync_queue, traveler_documents, travelers, trip_bookings, trip_media, trips, user_audit_log, users
-- Row counts at generation time: assignment_history=2, booking_event_trail=23, booking_status_history=61, ce_bookings=0, community_events=0, dm_copy_library=0, handoff_queue=3, interactions=33, language_templates=0, leads=9, sync_queue=29, traveler_documents=8, travelers=550, trip_bookings=60, trip_media=6, trips=47, user_audit_log=3, users=2

BEGIN;

CREATE TABLE IF NOT EXISTS "assignment_history" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "resource_type" VARCHAR(30) NOT NULL,
    "resource_id" VARCHAR(80) NOT NULL,
    "previous_user_id" INTEGER,
    "new_user_id" INTEGER,
    "assigned_by_user_id" INTEGER,
    "reason" TEXT,
    "request_id" VARCHAR(100),
    "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "booking_event_trail" (
    "event_id" VARCHAR(50) NOT NULL,
    "occurred_at" TIMESTAMP WITHOUT TIME ZONE,
    "event_type" VARCHAR(100),
    "event_label" VARCHAR(150),
    "traveler_id" VARCHAR(20),
    "lead_id" VARCHAR(50),
    "booking_id" VARCHAR(50),
    "trip_id" VARCHAR(50),
    "interaction_id" VARCHAR(50),
    "channel" VARCHAR(50),
    "actor" VARCHAR(50),
    "notes" TEXT,
    "metadata_json" TEXT,
    PRIMARY KEY ("event_id")
);

CREATE TABLE IF NOT EXISTS "booking_status_history" (
    "history_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "booking_id" VARCHAR(50) NOT NULL,
    "old_status" VARCHAR(50),
    "new_status" VARCHAR(50),
    "changed_at" TIMESTAMP WITHOUT TIME ZONE,
    "changed_by" VARCHAR(50),
    "change_source" VARCHAR(50),
    "notes" TEXT,
    PRIMARY KEY ("history_id")
);

CREATE TABLE IF NOT EXISTS "ce_bookings" (
    "booking_id" VARCHAR(50) NOT NULL,
    "event_id" VARCHAR(50),
    "event_name" VARCHAR(200),
    "traveler_id" VARCHAR(20),
    "traveler_name" VARCHAR(200),
    "status" VARCHAR(50),
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "notes" TEXT,
    PRIMARY KEY ("booking_id")
);

CREATE TABLE IF NOT EXISTS "community_events" (
    "event_id" VARCHAR(50) NOT NULL,
    "event_name" VARCHAR(200) NOT NULL,
    "date" DATE,
    "location" VARCHAR(200),
    "status" VARCHAR(50),
    "description" TEXT,
    "notes" TEXT,
    PRIMARY KEY ("event_id")
);

CREATE TABLE IF NOT EXISTS "dm_copy_library" (
    "message_key" VARCHAR(100) NOT NULL,
    "flow_key" VARCHAR(100),
    "step_key" VARCHAR(100),
    "channel" VARCHAR(50),
    "arabic_copy" TEXT,
    "english_copy" TEXT,
    "buttons_arabic" TEXT,
    "buttons_english" TEXT,
    "variables" VARCHAR(255),
    "source_sheet" VARCHAR(100),
    "active" BOOLEAN,
    "notes" TEXT,
    PRIMARY KEY ("message_key")
);

CREATE TABLE IF NOT EXISTS "handoff_queue" (
    "handoff_id" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "lead_id" VARCHAR(50),
    "traveler_id" VARCHAR(20),
    "trip_id" VARCHAR(50),
    "flow_key" VARCHAR(100),
    "reason" TEXT,
    "priority" VARCHAR(50),
    "channel" VARCHAR(50),
    "status" VARCHAR(50),
    "owner" VARCHAR(100),
    "assigned_to" VARCHAR(100),
    "notes" TEXT,
    PRIMARY KEY ("handoff_id")
);

CREATE TABLE IF NOT EXISTS "interactions" (
    "interaction_id" VARCHAR(50) NOT NULL,
    "timestamp" TIMESTAMP WITHOUT TIME ZONE,
    "channel" VARCHAR(50),
    "customer_name" VARCHAR(200),
    "raw_phone" VARCHAR(50),
    "integrated_whatsapp" VARCHAR(50),
    "phone_lookup_key" VARCHAR(50),
    "traveler_id" VARCHAR(20),
    "matched_row" INTEGER,
    "status_snapshot" VARCHAR(100),
    "intent" VARCHAR(100),
    "trip_type" VARCHAR(50),
    "suggested_trips" TEXT,
    "action_taken" TEXT,
    "handoff_required" BOOLEAN,
    "handoff_reason" TEXT,
    "agent_notes" TEXT,
    "flow_key" VARCHAR(100),
    "step_key" VARCHAR(100),
    "message_key" VARCHAR(100),
    "language" VARCHAR(20),
    "source_sheet" VARCHAR(100),
    "source_row" INTEGER,
    "outcome" TEXT,
    PRIMARY KEY ("interaction_id")
);

CREATE TABLE IF NOT EXISTS "language_templates" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "template_key" VARCHAR(100),
    "language" VARCHAR(20),
    "use_case" VARCHAR(100),
    "approved_copy" TEXT,
    "variables" VARCHAR(255),
    "status" VARCHAR(50),
    "notes" TEXT,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "leads" (
    "lead_id" VARCHAR(50) NOT NULL,
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE,
    "customer_name" VARCHAR(200),
    "raw_phone" VARCHAR(50),
    "integrated_whatsapp" VARCHAR(50),
    "phone_lookup_key" VARCHAR(50),
    "traveler_id" VARCHAR(20),
    "traveler_status" VARCHAR(50),
    "customer_tier" VARCHAR(50),
    "match_status" VARCHAR(50),
    "lead_stage" VARCHAR(100),
    "lead_source" VARCHAR(100),
    "channel" VARCHAR(50),
    "preferred_trip_type" VARCHAR(50),
    "interested_trip_ids" TEXT,
    "suggested_trip_ids" TEXT,
    "priority" VARCHAR(50),
    "follow_up_status" VARCHAR(100),
    "follow_up_due_date" DATE,
    "last_interaction_id" VARCHAR(50),
    "interaction_count" INTEGER,
    "handoff_required" BOOLEAN,
    "handoff_reason" TEXT,
    "notes" TEXT,
    "flow_key" VARCHAR(100),
    "current_step" VARCHAR(100),
    "language" VARCHAR(20),
    "trigger_keyword" VARCHAR(100),
    "waitlist_id" VARCHAR(50),
    "handoff_id" VARCHAR(50),
    "booking_id" VARCHAR(50),
    "source_sheet" VARCHAR(100),
    "source_row" INTEGER,
    "group_size" INTEGER DEFAULT 1,
    "passport_attachment_ref" TEXT,
    "passport_status" TEXT,
    "assigned_to" VARCHAR(100),
    "last_contact_at" TIMESTAMP WITHOUT TIME ZONE,
    "customer_response_status" VARCHAR(100),
    "assigned_to_user_id" INTEGER,
    "assigned_at" TIMESTAMP WITHOUT TIME ZONE,
    "assigned_by_user_id" INTEGER,
    PRIMARY KEY ("lead_id")
);

CREATE TABLE IF NOT EXISTS "sync_queue" (
    "mapping_name" TEXT NOT NULL,
    "record_id" TEXT NOT NULL,
    "status" TEXT DEFAULT 'pending' NOT NULL,
    "error_message" TEXT,
    "created_at" TEXT NOT NULL,
    "updated_at" TEXT NOT NULL,
    PRIMARY KEY ("mapping_name", "record_id")
);

CREATE TABLE IF NOT EXISTS "traveler_documents" (
    "document_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "traveler_id" VARCHAR(20) NOT NULL,
    "category" VARCHAR(50) DEFAULT 'document' NOT NULL,
    "file_name" VARCHAR(255) NOT NULL,
    "original_file_name" VARCHAR(255),
    "mime_type" VARCHAR(100),
    "file_extension" VARCHAR(20),
    "file_size" INTEGER,
    "storage_path" VARCHAR(500) NOT NULL,
    "uploaded_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "uploaded_by" VARCHAR(100),
    "passport_full_name" VARCHAR(200),
    "passport_number" VARCHAR(50),
    "passport_nationality" VARCHAR(100),
    "passport_expiry" DATE,
    "verification_status" VARCHAR(50) DEFAULT 'pending',
    "notes" TEXT,
    PRIMARY KEY ("document_id")
);

CREATE TABLE IF NOT EXISTS "travelers" (
    "traveler_id" VARCHAR(20) NOT NULL,
    "status" VARCHAR(50),
    "full_name" VARCHAR(200) NOT NULL,
    "first_name" VARCHAR(100),
    "last_name" VARCHAR(100),
    "birthday" DATE,
    "gender" VARCHAR(20),
    "nationality" VARCHAR(100),
    "phone_code" VARCHAR(10),
    "whatsapp_raw" VARCHAR(50),
    "email" VARCHAR(150),
    "community_whatsapp" VARCHAR(100),
    "residence" VARCHAR(150),
    "local_trips_count" INTEGER,
    "international_trips_count" INTEGER,
    "total_trips" INTEGER,
    "community_events_count" INTEGER,
    "lifetime_revenue" DOUBLE PRECISION,
    "notes" TEXT,
    "introduce_yourself" TEXT,
    "emergency_contact" VARCHAR(200),
    "emergency_phone" VARCHAR(50),
    "medical_notes" TEXT,
    "room_preference" VARCHAR(100),
    "rating" DOUBLE PRECISION,
    "integrated_whatsapp" VARCHAR(50),
    "normalized_whatsapp" VARCHAR(50),
    "phone_lookup_key" VARCHAR(50),
    "lead_source" VARCHAR(100),
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "last_contacted_at" TIMESTAMP WITHOUT TIME ZONE,
    "agent_notes" TEXT,
    "data_audit" TEXT,
    "primary_language" VARCHAR(20),
    "current_flow_key" VARCHAR(100),
    "current_step" VARCHAR(100),
    "last_lead_id" VARCHAR(50),
    "last_booking_id" VARCHAR(50),
    "passport_name" VARCHAR(200),
    "passport_number" VARCHAR(50),
    "passport_expiry" DATE,
    "passport_nationality" VARCHAR(100),
    "passport_attachment_ref" VARCHAR(300),
    PRIMARY KEY ("traveler_id")
);

CREATE TABLE IF NOT EXISTS "trip_bookings" (
    "booking_id" VARCHAR(50) NOT NULL,
    "trip_id" VARCHAR(50),
    "trip_name" VARCHAR(200),
    "traveler_id" VARCHAR(20),
    "traveler_name" VARCHAR(200),
    "room_type" VARCHAR(50),
    "flight_option" VARCHAR(50),
    "date_option" VARCHAR(50),
    "currency" VARCHAR(20),
    "booking_status" VARCHAR(50),
    "draft_created_at" TIMESTAMP WITHOUT TIME ZONE,
    "booking_source" VARCHAR(100),
    "lead_id" VARCHAR(50),
    "interaction_id" VARCHAR(50),
    "alert_id" VARCHAR(50),
    "payment_status" VARCHAR(100),
    "booking_notes" TEXT,
    "passport_required" INTEGER DEFAULT 0,
    "passport_status" TEXT,
    "group_size" INTEGER DEFAULT 1,
    "assigned_to" VARCHAR(100),
    "priority" VARCHAR(50),
    "next_follow_up_at" TIMESTAMP WITHOUT TIME ZONE,
    "next_action" VARCHAR(200),
    "last_contact_at" TIMESTAMP WITHOUT TIME ZONE,
    "customer_response_status" VARCHAR(100),
    "assigned_to_user_id" INTEGER,
    "assigned_at" TIMESTAMP WITHOUT TIME ZONE,
    "assigned_by_user_id" INTEGER,
    "room_group" VARCHAR(50),
    "boys_rooms_requested" INTEGER DEFAULT 0,
    "girls_rooms_requested" INTEGER DEFAULT 0,
    "room_requirements_json" TEXT,
    PRIMARY KEY ("booking_id")
);

CREATE TABLE IF NOT EXISTS "trip_media" (
    "media_id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "public_id" VARCHAR(36) NOT NULL,
    "trip_id" VARCHAR(50) NOT NULL,
    "storage_key" VARCHAR(500) NOT NULL,
    "public_url" VARCHAR(500) NOT NULL,
    "image_type" VARCHAR(20) DEFAULT 'gallery' NOT NULL,
    "alt_text" VARCHAR(255),
    "display_order" INTEGER DEFAULT 0 NOT NULL,
    "original_filename" VARCHAR(255),
    "mime_type" VARCHAR(100) NOT NULL,
    "file_extension" VARCHAR(10) NOT NULL,
    "file_size" INTEGER DEFAULT 0 NOT NULL,
    "uploaded_by_user_id" INTEGER,
    "uploaded_by_name" VARCHAR(100),
    "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    "is_active" BOOLEAN DEFAULT TRUE NOT NULL,
    "verification_status" VARCHAR(50) DEFAULT 'verified' NOT NULL,
    PRIMARY KEY ("media_id")
);

CREATE TABLE IF NOT EXISTS "trips" (
    "trip_id" VARCHAR(50) NOT NULL,
    "trip_name" VARCHAR(200) NOT NULL,
    "type" VARCHAR(50),
    "year" INTEGER,
    "trip_leader" VARCHAR(100),
    "start_date" DATE,
    "end_date" DATE,
    "sales_status" VARCHAR(50),
    "data_audit" TEXT,
    "trip_window_status" VARCHAR(50),
    "trip_availability_note" TEXT,
    "next_reengage_date" DATE,
    "single_total" INTEGER,
    "double_total" INTEGER,
    "triple_total" INTEGER,
    "single_remaining" INTEGER,
    "double_remaining" INTEGER,
    "triple_remaining" INTEGER,
    "draft_holds_single" INTEGER,
    "draft_holds_double" INTEGER,
    "draft_holds_triple" INTEGER,
    "boys_double" INTEGER,
    "girls_double" INTEGER,
    "boys_triple" INTEGER,
    "girls_triple" INTEGER,
    "public_price" VARCHAR(200),
    "public_description" TEXT,
    "sales_notes" TEXT,
    "draft_holds_boys_double" INTEGER DEFAULT 0,
    "draft_holds_girls_double" INTEGER DEFAULT 0,
    "draft_holds_boys_triple" INTEGER DEFAULT 0,
    "draft_holds_girls_triple" INTEGER DEFAULT 0,
    PRIMARY KEY ("trip_id")
);

CREATE TABLE IF NOT EXISTS "user_audit_log" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "actor_user_id" INTEGER,
    "target_user_id" INTEGER,
    "action" VARCHAR(80) NOT NULL,
    "details" TEXT,
    "created_at" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "users" (
    "id" INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    "username" VARCHAR(80) NOT NULL,
    "password_hash" VARCHAR(200) NOT NULL,
    "email" VARCHAR(120),
    "is_active" BOOLEAN,
    "created_at" TIMESTAMP WITHOUT TIME ZONE,
    "full_name" VARCHAR(200),
    "role" VARCHAR(50) DEFAULT 'agent' NOT NULL,
    "updated_at" TIMESTAMP WITHOUT TIME ZONE,
    "last_login_at" TIMESTAMP WITHOUT TIME ZONE,
    PRIMARY KEY ("id")
);


CREATE INDEX IF NOT EXISTS "ix_assignment_history_resource" ON "assignment_history" ("resource_id");
CREATE INDEX IF NOT EXISTS "idx_handoff_queue_lead_status" ON "handoff_queue" ("lead_id", "status");
CREATE INDEX IF NOT EXISTS "idx_handoff_queue_traveler_status" ON "handoff_queue" ("traveler_id", "status");
CREATE INDEX IF NOT EXISTS "idx_handoff_queue_status_created" ON "handoff_queue" ("status", "created_at");
CREATE INDEX IF NOT EXISTS "ix_leads_assigned_to_user_id" ON "leads" ("assigned_to_user_id");
CREATE INDEX IF NOT EXISTS "ix_trip_bookings_assigned_to_user_id" ON "trip_bookings" ("assigned_to_user_id");
CREATE INDEX IF NOT EXISTS "ix_trip_media_verification_status" ON "trip_media" ("verification_status");
CREATE INDEX IF NOT EXISTS "ix_trip_media_is_active" ON "trip_media" ("is_active");
CREATE INDEX IF NOT EXISTS "ix_trip_media_image_type" ON "trip_media" ("image_type");
CREATE INDEX IF NOT EXISTS "ix_trip_media_public_id" ON "trip_media" ("public_id");
CREATE INDEX IF NOT EXISTS "ix_trip_media_trip_id" ON "trip_media" ("trip_id");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_trip_media_storage_key" ON "trip_media" ("storage_key");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_trip_media_public_id" ON "trip_media" ("public_id");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_users_email" ON "users" ("email");
CREATE UNIQUE INDEX IF NOT EXISTS "ux_users_username" ON "users" ("username");
COMMIT;
