from __future__ import annotations


TRIPS_SHEET_NAME = "Trips"
TRIPS_HEADER_ROW = 2
TRIPS_DATA_START_ROW = 3

# The workbook keeps trip inventory in fixed columns; we map only the fields
# that Phase 1/2 must keep in sync between the system DB and the operational sheet.
TRIPS_SHEET_COLUMNS = {
    "trip_id": 1,
    "trip_name": 2,
    "type": 3,
    "year": 4,
    "trip_leader": 5,
    "start_date": 6,
    "end_date": 7,
    "single_total": 8,
    "double_total": 9,
    "triple_total": 10,
    "single_remaining": 11,
    "double_remaining": 12,
    "triple_remaining": 13,
    "boys_double": 14,
    "girls_double": 15,
    "boys_triple": 16,
    "girls_triple": 17,
    "sales_status": 26,
    "data_audit": 27,
}

BOOKING_EVENT_TRAIL_SHEET_NAME = "Booking Event Trail"
BOOKING_EVENT_TRAIL_HEADERS = [
    "Event ID",
    "Occurred At",
    "Event Type",
    "Event Label",
    "Traveler ID",
    "Lead ID",
    "Booking ID",
    "Trip ID",
    "Interaction ID",
    "Channel",
    "Actor",
    "Notes",
    "Metadata",
]

SHEET_TABLE_MAPPINGS = {
    "Trips": {
        "sheet_name": TRIPS_SHEET_NAME,
        "header_row": TRIPS_HEADER_ROW,
        "data_start_row": TRIPS_DATA_START_ROW,
        "columns": TRIPS_SHEET_COLUMNS,
    },
    "Travelers": {
        "sheet_name": "Travelers",
        "header_row": 1,
        "columns": {
            "traveler_id": "Traveler ID",
            "status": "Status",
            "full_name": "Full Name",
            "birthday": "Birthday",
            "gender": "Gender",
            "nationality": "Nationality",
            "phone_code": "Code",
            "whatsapp_raw": "WhatsApp",
            "email": "Email",
            "community_whatsapp": "Community Whatsapp",
            "residence": "Residence",
            "local_trips_count": "Loc. Trips",
            "international_trips_count": "Int. Trips",
            "total_trips": "Total trips",
            "community_events_count": "Comm. Events",
            "lifetime_revenue": "Lifetime Revenue",
            "preferred_currency": "Preferred Currency",
            "notes": "Notes",
            "introduce_yourself": "Introduce yourself",
            "emergency_contact": "Emergency Contact",
            "emergency_phone": "Emergency Phone",
            "integrated_whatsapp": "Integrated WhatsApp",
            "phone_lookup_key": "Phone Lookup Key",
            "lead_source": "Lead Source",
            "created_at": "Created At",
            "last_contacted_at": "Last Contacted At",
            "agent_notes": "Agent Notes",
            "data_audit": "Data Audit",
        },
    },
    "Leads": {
        "sheet_name": "Leads",
        "header_row": 1,
        "columns": {
            "lead_id": "Lead ID",
            "created_at": "Created At",
            "updated_at": "Updated At",
            "customer_name": "Customer Name",
            "raw_phone": "Raw Phone",
            "integrated_whatsapp": "Integrated WhatsApp",
            "phone_lookup_key": "Phone Lookup Key",
            "traveler_id": "Traveler ID",
            "traveler_status": "Traveler Status",
            "customer_tier": "Customer Tier",
            "match_status": "Match Status",
            "lead_stage": "Lead Stage",
            "lead_source": "Lead Source",
            "channel": "Channel",
            "preferred_trip_type": "Preferred Trip Type",
            "interested_trip_ids": "Interested Trip IDs",
            "suggested_trip_ids": "Suggested Trip IDs",
            "priority": "Priority",
            "follow_up_status": "Follow Up Status",
            "follow_up_due_date": "Follow Up Due Date",
            "last_interaction_id": "Last Interaction ID",
            "interaction_count": "Interaction Count",
            "handoff_required": "Handoff Required",
            "handoff_reason": "Handoff Reason",
            "notes": "Notes",
            "flow_key": "Flow Key",
            "current_step": "Current Step",
            "language": "Language",
            "booking_id": "Booking ID",
        },
    },
    "Interactions": {
        "sheet_name": "Interactions",
        "header_row": 1,
        "columns": {
            "interaction_id": "Interaction ID",
            "timestamp": "Timestamp",
            "channel": "Channel",
            "customer_name": "Customer Name",
            "raw_phone": "Raw Phone",
            "integrated_whatsapp": "Integrated WhatsApp",
            "phone_lookup_key": "Phone Lookup Key",
            "traveler_id": "Traveler ID",
            "matched_row": "Matched Row",
            "status_snapshot": "Status Snapshot",
            "intent": "Intent",
            "trip_type": "Trip Type",
            "suggested_trips": "Suggested Trips",
            "action_taken": "Action Taken",
            "handoff_required": "Handoff Required",
            "handoff_reason": "Handoff Reason",
            "agent_notes": "Agent Notes",
            "flow_key": "Flow Key",
            "step_key": "Step Key",
            "message_key": "Message Key",
            "language": "Language",
            "outcome": "Outcome",
        },
    },
    "Trip Bookings": {
        "sheet_name": "Trip Bookings",
        "header_row": 2,
        "columns": {
            "booking_id": "Booking ID",
            "trip_id": "Trip ID",
            "trip_name": "Trip Name",
            "traveler_id": "Traveler ID",
            "traveler_name": "Traveler Name",
            "room_type": "Room Type",
            "flight_option": "Flight Option",
            "date_option": "Date Option",
            "currency": "Currency",
            "booking_status": "Booking Status",
            "draft_created_at": "Draft Created At",
            "booking_source": "Booking Source",
            "lead_id": "Lead ID",
            "interaction_id": "Interaction ID",
            "alert_id": "Alert ID",
            "payment_status": "Payment Status",
            "booking_notes": "Booking Notes",
        },
    },
    "Handoff Queue": {
        "sheet_name": "Handoff Queue",
        "header_row": 1,
        "columns": {
            "handoff_id": "Handoff ID",
            "lead_id": "Lead ID",
            "traveler_id": "Traveler ID",
            "trip_id": "Trip ID",
            "reason": "Reason",
            "priority": "Priority",
            "channel": "Channel",
            "status": "Status",
            "notes": "Notes",
        },
    },
    "Booking Event Trail": {
        "sheet_name": BOOKING_EVENT_TRAIL_SHEET_NAME,
        "header_row": 1,
        "columns": {
            "event_id": "Event ID",
            "occurred_at": "Occurred At",
            "event_type": "Event Type",
            "event_label": "Event Label",
            "traveler_id": "Traveler ID",
            "lead_id": "Lead ID",
            "booking_id": "Booking ID",
            "trip_id": "Trip ID",
            "interaction_id": "Interaction ID",
            "channel": "Channel",
            "actor": "Actor",
            "notes": "Notes",
            "metadata_json": "Metadata",
        },
    },
}
