"""Initial migration

Revision ID: 7835d45ae61b
Revises: 
Create Date: 2026-05-14 16:02:04.591952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7835d45ae61b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('community_events',
    sa.Column('event_id', sa.String(length=50), nullable=False),
    sa.Column('event_name', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('dm_copy_library',
    sa.Column('message_key', sa.String(length=100), nullable=False),
    sa.Column('flow_key', sa.String(length=100), nullable=True),
    sa.Column('step_key', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('arabic_copy', sa.Text(), nullable=True),
    sa.Column('english_copy', sa.Text(), nullable=True),
    sa.Column('buttons_arabic', sa.Text(), nullable=True),
    sa.Column('buttons_english', sa.Text(), nullable=True),
    sa.Column('variables', sa.String(length=255), nullable=True),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('message_key')
    )
    op.create_table('language_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('template_key', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('use_case', sa.String(length=100), nullable=True),
    sa.Column('approved_copy', sa.Text(), nullable=True),
    sa.Column('variables', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('travelers',
    sa.Column('traveler_id', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('birthday', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('phone_code', sa.String(length=10), nullable=True),
    sa.Column('whatsapp_raw', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('community_whatsapp', sa.String(length=100), nullable=True),
    sa.Column('residence', sa.String(length=150), nullable=True),
    sa.Column('local_trips_count', sa.Integer(), nullable=True),
    sa.Column('international_trips_count', sa.Integer(), nullable=True),
    sa.Column('total_trips', sa.Integer(), nullable=True),
    sa.Column('community_events_count', sa.Integer(), nullable=True),
    sa.Column('lifetime_revenue', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('introduce_yourself', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=200), nullable=True),
    sa.Column('emergency_phone', sa.String(length=50), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('room_preference', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('integrated_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('normalized_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('phone_lookup_key', sa.String(length=50), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_contacted_at', sa.DateTime(), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('data_audit', sa.Text(), nullable=True),
    sa.Column('primary_language', sa.String(length=20), nullable=True),
    sa.Column('current_flow_key', sa.String(length=100), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('last_lead_id', sa.String(length=50), nullable=True),
    sa.Column('last_booking_id', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('traveler_id')
    )
    op.create_table('trips',
    sa.Column('trip_id', sa.String(length=50), nullable=False),
    sa.Column('trip_name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('trip_leader', sa.String(length=100), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('sales_status', sa.String(length=50), nullable=True),
    sa.Column('data_audit', sa.Text(), nullable=True),
    sa.Column('trip_window_status', sa.String(length=50), nullable=True),
    sa.Column('trip_availability_note', sa.Text(), nullable=True),
    sa.Column('next_reengage_date', sa.Date(), nullable=True),
    sa.Column('single_total', sa.Integer(), nullable=True),
    sa.Column('double_total', sa.Integer(), nullable=True),
    sa.Column('triple_total', sa.Integer(), nullable=True),
    sa.Column('single_remaining', sa.Integer(), nullable=True),
    sa.Column('double_remaining', sa.Integer(), nullable=True),
    sa.Column('triple_remaining', sa.Integer(), nullable=True),
    sa.Column('draft_holds_single', sa.Integer(), nullable=True),
    sa.Column('draft_holds_double', sa.Integer(), nullable=True),
    sa.Column('draft_holds_triple', sa.Integer(), nullable=True),
    sa.Column('public_price', sa.String(length=200), nullable=True),
    sa.Column('public_description', sa.Text(), nullable=True),
    sa.Column('sales_notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('trip_id')
    )
    op.create_table('ce_bookings',
    sa.Column('booking_id', sa.String(length=50), nullable=False),
    sa.Column('event_id', sa.String(length=50), nullable=True),
    sa.Column('event_name', sa.String(length=200), nullable=True),
    sa.Column('traveler_id', sa.String(length=20), nullable=True),
    sa.Column('traveler_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['community_events.event_id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.traveler_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('interactions',
    sa.Column('interaction_id', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('raw_phone', sa.String(length=50), nullable=True),
    sa.Column('integrated_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('phone_lookup_key', sa.String(length=50), nullable=True),
    sa.Column('traveler_id', sa.String(length=20), nullable=True),
    sa.Column('matched_row', sa.Integer(), nullable=True),
    sa.Column('status_snapshot', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('trip_type', sa.String(length=50), nullable=True),
    sa.Column('suggested_trips', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.Text(), nullable=True),
    sa.Column('handoff_required', sa.Boolean(), nullable=True),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('agent_notes', sa.Text(), nullable=True),
    sa.Column('flow_key', sa.String(length=100), nullable=True),
    sa.Column('step_key', sa.String(length=100), nullable=True),
    sa.Column('message_key', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.traveler_id'], ),
    sa.PrimaryKeyConstraint('interaction_id')
    )
    op.create_table('leads',
    sa.Column('lead_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=True),
    sa.Column('raw_phone', sa.String(length=50), nullable=True),
    sa.Column('integrated_whatsapp', sa.String(length=50), nullable=True),
    sa.Column('phone_lookup_key', sa.String(length=50), nullable=True),
    sa.Column('traveler_id', sa.String(length=20), nullable=True),
    sa.Column('traveler_status', sa.String(length=50), nullable=True),
    sa.Column('customer_tier', sa.String(length=50), nullable=True),
    sa.Column('match_status', sa.String(length=50), nullable=True),
    sa.Column('lead_stage', sa.String(length=100), nullable=True),
    sa.Column('lead_source', sa.String(length=100), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('preferred_trip_type', sa.String(length=50), nullable=True),
    sa.Column('interested_trip_ids', sa.Text(), nullable=True),
    sa.Column('suggested_trip_ids', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('follow_up_status', sa.String(length=100), nullable=True),
    sa.Column('follow_up_due_date', sa.Date(), nullable=True),
    sa.Column('last_interaction_id', sa.String(length=50), nullable=True),
    sa.Column('interaction_count', sa.Integer(), nullable=True),
    sa.Column('handoff_required', sa.Boolean(), nullable=True),
    sa.Column('handoff_reason', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('flow_key', sa.String(length=100), nullable=True),
    sa.Column('current_step', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=20), nullable=True),
    sa.Column('trigger_keyword', sa.String(length=100), nullable=True),
    sa.Column('waitlist_id', sa.String(length=50), nullable=True),
    sa.Column('handoff_id', sa.String(length=50), nullable=True),
    sa.Column('booking_id', sa.String(length=50), nullable=True),
    sa.Column('source_sheet', sa.String(length=100), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.traveler_id'], ),
    sa.PrimaryKeyConstraint('lead_id')
    )
    op.create_table('trip_bookings',
    sa.Column('booking_id', sa.String(length=50), nullable=False),
    sa.Column('trip_id', sa.String(length=50), nullable=True),
    sa.Column('trip_name', sa.String(length=200), nullable=True),
    sa.Column('traveler_id', sa.String(length=20), nullable=True),
    sa.Column('traveler_name', sa.String(length=200), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('flight_option', sa.String(length=50), nullable=True),
    sa.Column('date_option', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=20), nullable=True),
    sa.Column('booking_status', sa.String(length=50), nullable=True),
    sa.Column('draft_created_at', sa.DateTime(), nullable=True),
    sa.Column('booking_source', sa.String(length=100), nullable=True),
    sa.Column('lead_id', sa.String(length=50), nullable=True),
    sa.Column('interaction_id', sa.String(length=50), nullable=True),
    sa.Column('alert_id', sa.String(length=50), nullable=True),
    sa.Column('payment_status', sa.String(length=100), nullable=True),
    sa.Column('booking_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.traveler_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('booking_id')
    )
    op.create_table('handoff_queue',
    sa.Column('handoff_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('lead_id', sa.String(length=50), nullable=True),
    sa.Column('traveler_id', sa.String(length=20), nullable=True),
    sa.Column('trip_id', sa.String(length=50), nullable=True),
    sa.Column('flow_key', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=100), nullable=True),
    sa.Column('assigned_to', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.lead_id'], ),
    sa.ForeignKeyConstraint(['traveler_id'], ['travelers.traveler_id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.trip_id'], ),
    sa.PrimaryKeyConstraint('handoff_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('handoff_queue')
    op.drop_table('trip_bookings')
    op.drop_table('leads')
    op.drop_table('interactions')
    op.drop_table('ce_bookings')
    op.drop_table('trips')
    op.drop_table('travelers')
    op.drop_table('language_templates')
    op.drop_table('dm_copy_library')
    op.drop_table('community_events')
    # ### end Alembic commands ###
